import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, MapPin, Phone, ShieldCheck } from "lucide-react";

const images = {
  hero: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=2200&q=85",
  workshop: "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&w=1600&q=82",
  repair: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1400&q=82",
  car: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=82"
};
const services=[["01","General Car Service & Repairs","Routine maintenance and mechanical repair enquiries.",images.car,"/services/car-service/"],["02","Car AC Service & Repair","A focused route for AC service and repair.",images.hero,"/services/car-ac-repair/"],["03","Denting, Painting & Accident Repair","Bodywork, restoration and insurance assistance.",images.repair,"/services/accident-repair/"],["04","Wheel Alignment, Balancing & Tyre","Alignment, balancing, tyre repair and rim repair.",images.workshop,"/services/wheel-alignment/"],["05","Automobile Spare Parts","Inquiry-first parts assistance for your vehicle.",images.car,"/spare-parts/"]];

export default function Home(){return <main>
<section className="hero"><div className="hero-media" style={{backgroundImage:"url("+images.hero+")"}}/><div className="hero-shade"/><div className="hero-grid"/><div className="wrap hero-inner"><div className="hero-meta"><span>IRINJALAKUDA · THRISSUR · KERALA</span><span>INDEPENDENT / MULTI-BRAND</span><span>EST. 1996 · CONFIRMATION PENDING</span></div><div className="hero-kicker">Automotive service / parts / repair</div><h1 className="hero-title"><span>CARE.</span><span className="ghost">REPAIR.</span><span>RESTORE.</span></h1><div className="hero-bottom"><p>Professional automotive service for the moments when your vehicle needs someone who knows what to do next.</p><a className="circle-link" href="#services"><ArrowDownRight size={20}/></a></div><div className="hero-stats"><div><b>1996</b><span>established · confirm</span></div><div><b>05</b><span>core service pillars</span></div><div><b>01</b><span>local workshop</span></div></div></div></section>
<section className="section"><div className="wrap split"><div><span className="eyebrow">01 / The workshop</span><p className="side-note">The digital experience should feel like walking into a well-run professional workshop: clear, capable, technical and easy to deal with.</p></div><div><h2 className="display">Built around <span className="faded">the work.</span></h2><div className="lead-row"><p className="lead">Asian Automobiles brings service/repair and automobile parts together under one local business. The new site turns that offline proposition into clear service journeys, proof, insurance assistance and frictionless contact paths.</p><a className="text-link" href="/about/">About Asian Automobiles <ArrowUpRight size={16}/></a></div></div></div></section>
<section id="services" className="section services"><div className="wrap"><div className="section-head"><div><span className="eyebrow">02 / What we do</span><h2 className="display">Services <span className="faded">without the noise.</span></h2></div><span className="section-index">01—05</span></div><div className="service-list">{services.map(([n,t,d,img,href])=><a className="service-row" href={href} key={t}><span className="service-num">{n}</span><div><h3>{t}</h3><p>{d}</p></div><span className="service-copy">{d}</span><span className="service-arrow"><ChevronRight size={20}/></span><span className="service-preview"><img src={img} alt=""/></span></a>)}</div><a className="outline-link" href="/services/">View all services <ArrowUpRight size={15}/></a></div></section>
<section className="section dark"><div className="wrap"><div className="section-head"><div><span className="eyebrow light">03 / Proof of place</span><h2 className="display light">The shop <span className="faded">behind the service.</span></h2></div><p className="dark-note">Real workshop photography should become the primary visual asset. These images are temporary placeholders for the UI.</p></div><div className="photo-grid"><figure className="photo large"><img src={images.workshop} alt="Automotive workshop"/><figcaption><span>FACILITY / 01</span><b>Workshop floor & service environment</b></figcaption></figure><figure className="photo"><img src={images.repair} alt="Automotive repair"/><figcaption><span>CRAFT / 02</span><b>Repair activity & technical work</b></figcaption></figure></div></div></section>
<section className="section"><div className="wrap split"><div><span className="eyebrow">04 / A clearer journey</span><p className="side-note">The exact internal workflow must be confirmed before this is presented as an operational promise.</p></div><div><h2 className="display">From contact <span className="faded">to handover.</span></h2><div className="process-list">{[["01","Contact","Tell us what your vehicle needs."],["02","Assess","Inspection and diagnosis — final workflow to be confirmed."],["03","Service","Repair/service according to the agreed scope."],["04","Handover","Collect the vehicle and understand the next step."]].map(([n,t,d])=><div className="process-row" key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div><Check size={18}/></div>)}</div></div></div></section>
<section className="section insurance"><div className="wrap insurance-box"><div><span className="eyebrow">05 / Insurance assistance</span><h2 className="display">Accidents are stressful. <span className="faded">The next step shouldn't be.</span></h2><p className="lead">A dedicated route for accident repair assistance, damage photos and insurer coordination. The supplied research references New India Assurance and United India Insurance; current participation must be verified before launch.</p><a className="dark-link" href="/insurance/">Insurance assistance <ArrowUpRight size={16}/></a></div><div className="shield"><ShieldCheck size={42}/><span>Cashless repair pathway</span><small>VERIFY NETWORK BEFORE PUBLISHING</small></div></div></section>
<section className="section dark"><div className="wrap"><div className="section-head"><div><span className="eyebrow light">06 / Customer proof</span><h2 className="display light">Reviews <span className="faded">with context.</span></h2></div><a className="dark-link" href="/reviews/">All reviews <ArrowUpRight size={16}/></a></div><div className="review-track">{["Selected attributable customer reviews will live here once sources and consent are approved.","Real customer stories can become case studies with before/after context where permission exists.","The website will never fabricate testimonials or turn a review into an operational promise."].map((t,i)=><article className="review" key={i}><div className="review-top"><span>{"0"+(i+1)}</span><span>SOURCE / DATE</span></div><p>“{t}”</p><span className="review-author">ATTRIBUTION REQUIRED</span></article>)}</div></div></section>
<section className="section contact"><div className="wrap contact-grid"><div><span className="eyebrow">07 / Find us</span><h2 className="display">Come by. <span className="faded">Talk cars.</span></h2><p className="lead">283 / V-526, Govt Rest House, Kattoor Road, Irinjalakuda, Thrissur — 680121, Kerala.</p><div className="contact-actions"><a className="primary-link" href="tel:+919349002038"><Phone size={16}/>Call now</a><a className="outline-link" href="/contact/">Directions & contact <ArrowUpRight size={15}/></a></div></div><div className="contact-card"><MapPin size={20}/><span>IRINJALAKUDA<br/>THRISSUR · KERALA</span><small>Hours are intentionally not published until the conflicting directory listings are confirmed.</small></div></div></section>
<section className="final"><div className="wrap"><span className="eyebrow light">Ready when the vehicle is.</span><h2 className="display light">Book a <span className="faded">service.</span></h2><div className="final-actions"><a className="primary-link" href="/book-service/">Book a Service <ArrowUpRight size={16}/></a><a className="light-link" href="/request-quote/">Request a Quote <ArrowUpRight size={16}/></a></div></div></section>
</main>}