import Link from "next/link"; import {ArrowLeft,ArrowUpRight,CheckCircle2,CalendarDays,Phone,Upload} from "lucide-react";
const pages:Record<string,{eyebrow:string,title:string,intro:string,items:string[]}>={
about:{eyebrow:"About Asian Automobiles",title:"A clearer digital home for an established workshop.",intro:"Frontend placeholder for the Asian Automobiles story, business model, facility and people. Verified history and team information will be inserted after client confirmation.",items:["Established 1996 — pending final confirmation","Independent multi-brand service center positioning","Automobile parts and workshop services","Real facility photography placeholder"]},
services:{eyebrow:"Services",title:"Automotive service, organised around what you need.",intro:"Explore dedicated service journeys instead of one generic service page.",items:["General Car Service & Repairs","Car AC Service & Repair","Denting, Painting & Accident Repair","Wheel Alignment, Balancing & Tyre Services","Automobile Spare Parts"]},
insurance:{eyebrow:"Insurance Assistance",title:"A direct path after an accident.",intro:"Dedicated frontend journey for insurance-repair enquiries. Current insurer participation and exact workflow remain confirmation items.",items:["Accident repair assistance","Damage photo upload placeholder","Insurer details placeholder","Survey / approval coordination placeholder"]},
facilities:{eyebrow:"Our Facilities",title:"See the workshop behind the work.",intro:"Final version will use original photography of the workshop floor, service bays, alignment equipment, parts inventory and customer-facing spaces.",items:["Workshop floor","Service bays","Alignment equipment","Parts inventory","Customer-facing areas"]},
gallery:{eyebrow:"Gallery",title:"Real work. Real workshop.",intro:"Filterable gallery for workshop, repairs, parts, team, exterior and completed work.",items:["Workshop","Repairs","Parts","Team","Exterior","Completed Work"]},
reviews:{eyebrow:"Reviews & Customer Stories",title:"Proof from the people who came through the doors.",intro:"Review cards are placeholders until attributable reviews and customer consent are supplied.",items:["Attributable review source","Review date","Customer story","Consent status"]},
contact:{eyebrow:"Contact & Directions",title:"Find the workshop. Start the conversation.",intro:"283 / V-526, Govt Rest House, Kattoor Road, Irinjalakuda, Thrissur - 680121, Kerala.",items:["Phone: +91 9349002038","Phone: 0480 2828167","WhatsApp: placeholder","Opening hours: confirm before launch"]},
faq:{eyebrow:"FAQ",title:"Answers without the guesswork.",intro:"Only verified or client-approved answers will be published here.",items:["Services","Insurance","Vehicle brands","Location","Booking","Parts"]},
"spare-parts":{eyebrow:"Automobile Spare Parts",title:"Parts enquiries, made simple.",intro:"Inquiry-first parts experience. Live inventory or commerce can be connected later.",items:["Part requirement","Vehicle make / model","Quantity","Notes","Call / WhatsApp"]}};
const services:Record<string,{eyebrow:string,title:string,intro:string,items:string[]}>={
"car-service":{eyebrow:"General Car Service & Repairs",title:"Keep the essentials running right.",intro:"Dedicated page for routine maintenance and mechanical repair enquiries.",items:["Inspection","Diagnosis","Repair / service","Customer handover"]},
"car-ac-repair":{eyebrow:"Car AC Service & Repair",title:"A focused path for AC issues.",intro:"Clear information and a direct enquiry CTA for car AC service and repair.",items:["AC issue enquiry","Inspection placeholder","Repair / service","Book or call"]},
"accident-repair":{eyebrow:"Denting, Painting & Accident Repair",title:"From damage to the next step.",intro:"Accident-repair journey with a direct bridge into insurance assistance and photo enquiries.",items:["Damage description","Photo upload","Repair enquiry","Insurance assistance"]},
"denting-painting":{eyebrow:"Denting & Painting",title:"Bodywork with a clear process.",intro:"Frontend placeholder for denting, painting and restoration information.",items:["Damage assessment","Repair scope","Painting","Handover"]},
"wheel-alignment":{eyebrow:"Wheel Alignment, Balancing & Tyre Services",title:"Straighten out the details.",intro:"Dedicated journey for alignment, balancing, tyre repair and rim repair.",items:["Wheel alignment","Wheel balancing","Tyre repair / puncture","Rim repair"]},
"tyre-services":{eyebrow:"Tyre Services",title:"Better contact with the road.",intro:"Frontend placeholder for tyre and balancing enquiries.",items:["Tyre enquiry","Balancing","Repair","Booking"]}};
function Form({quote}:{quote:boolean}){return <div className="border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-5 md:grid-cols-2">{["Name","Phone","Vehicle make / model","Service needed"].map(x=><label key={x} className="text-xs font-bold uppercase tracking-wider text-slate-500">{x}<input className="mt-2 w-full border border-slate-200 bg-slate-50 px-4 py-3.5 text-sm outline-none focus:border-[#1769ff]" placeholder={x}/></label>)}<label className="text-xs font-bold uppercase tracking-wider text-slate-500 md:col-span-2">Notes<textarea className="mt-2 min-h-28 w-full border border-slate-200 bg-slate-50 px-4 py-3.5 text-sm outline-none focus:border-[#1769ff]" placeholder="Tell us what you need..."/></label>{quote&&<label className="flex cursor-pointer items-center gap-3 border border-dashed border-slate-300 p-4 text-sm text-slate-500 md:col-span-2"><Upload size={18}/>Upload damage / reference photos (placeholder)</label>}</div><button className="mt-6 inline-flex items-center gap-2 bg-[#1769ff] px-6 py-4 text-sm font-bold text-white">Submit enquiry<ArrowUpRight size={16}/></button><p className="mt-3 text-xs text-slate-400">Frontend only — submission routing will be connected later.</p></div>}
export default async function Page({params}:{params:Promise<{slug?:string[]}>}){const{slug=[]}=await params;const key=slug.join("/");if(key==="book-service"||key==="request-quote"){const quote=key==="request-quote";return <main className="min-h-screen bg-[#f5f7fa] pb-24 pt-36"><div className="container-xl max-w-5xl"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/>Back home</Link><div className="mb-10"><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-[#1769ff]">{quote?"Request a Quote":"Book a Service"}</p><h1 className="display text-6xl font-semibold md:text-8xl">{quote?"Tell us what needs fixing.":"Let's book your service."}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-500">Frontend placeholder. The form, routing and CRM will be connected after the UI is approved.</p></div><Form quote={quote}/></div></main>}const data=services[key]||pages[key];if(!data)return <main className="min-h-screen px-6 pb-24 pt-40"><div className="container-xl"><p className="text-sm text-[#1769ff]">404</p><h1 className="display mt-3 text-7xl font-semibold">Page not found.</h1><Link href="/" className="mt-8 inline-flex bg-[#0b1220] px-5 py-3 text-sm font-semibold text-white">Back home</Link></div></main>;return <main className="bg-[#f5f7fa] pb-24 pt-36"><section className="container-xl"><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-[#1769ff]">{data.eyebrow}</p><h1 className="display max-w-5xl text-6xl font-semibold md:text-8xl">{data.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-500">{data.intro}</p><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.items.map((item,i)=><div key={item} className="border border-slate-200 bg-white p-7"><span className="font-mono text-xs text-slate-400">0{i+1}</span><div className="mt-10 flex items-center gap-3 text-lg font-semibold"><CheckCircle2 size={19} className="text-[#1769ff]"/>{item}</div></div>)}</div></section><section className="container-xl mt-20"><div className="bg-[#07101c] p-8 text-white md:p-12"><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#65d6ef]">Frontend placeholder</p><h2 className="mt-4 text-3xl font-semibold">Ready for the real content.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-white/50">Forms, CMS, integrations, analytics and confirmed business details will be connected in the next phase.</p></div><div className="flex flex-wrap gap-3"><Link href="/book-service" className="inline-flex items-center gap-2 bg-[#1769ff] px-5 py-3 text-sm font-semibold">Book<CalendarDays size={16}/></Link><Link href="/contact" className="inline-flex items-center gap-2 border border-white/15 px-5 py-3 text-sm font-semibold"><Phone size={16}/>Call</Link></div></div></div></section></main>}