import { ArrowUpRight, ArrowLeft, Check, Phone, Upload } from "lucide-react";
import Link from "next/link";

const pages:Record<string,{eyebrow:string;title:string;intro:string;items:string[]}>={
about:{eyebrow:"About Asian Automobiles",title:"A clearer digital home for an established workshop.",intro:"The business proposition is built around service/repair and automobile parts. Verified history, leadership and facility details will be added after client confirmation.",items:["Established 1996 — confirm before final copy","Independent multi-brand service center positioning","Service / repair + automobile parts","Real facility photography"]},
services:{eyebrow:"Services",title:"Automotive service, organised around what you need.",intro:"Dedicated service journeys for the major verified categories identified in the website blueprint.",items:["General Car Service & Repairs","Car AC Service & Repair","Denting, Painting & Accident Repair","Wheel Alignment, Balancing & Tyre Services","Automobile Spare Parts"]},
insurance:{eyebrow:"Cashless Insurance Repairs",title:"A direct path after an accident.",intro:"Current insurer relationships and the exact internal process must be verified before publication.",items:["Accident repair assistance","Damage photo upload","Survey / approval coordination","Repair and handover"]},
facilities:{eyebrow:"Our Facilities",title:"See the workshop behind the work.",intro:"Original photography should show the workshop floor, service bays, alignment equipment, parts inventory and customer-facing spaces.",items:["Workshop floor","Service bays","Alignment equipment","Parts inventory","Customer-facing areas"]},
gallery:{eyebrow:"Gallery",title:"Real work. Real workshop.",intro:"Filterable visual proof for workshop, repairs, parts, team, exterior and completed work.",items:["Workshop","Repairs","Parts","Team","Exterior","Completed Work"]},
reviews:{eyebrow:"Reviews & Customer Stories",title:"Proof from the people who came through the doors.",intro:"Attributable public reviews and consented customer stories should be added with source and date. No fabricated testimonials.",items:["Reviewer + source","Review date","Customer story","Consent / usage status"]},
contact:{eyebrow:"Contact & Directions",title:"Find the workshop. Start the conversation.",intro:"283 / V-526, Govt Rest House, Kattoor Road, Irinjalakuda, Thrissur - 680121, Kerala.",items:["+91 9349002038","0480 2828167","WhatsApp — confirm official business number","Opening hours — confirm before launch"]},
faq:{eyebrow:"FAQ",title:"Answers without the guesswork.",intro:"Every published answer must be sourced or client-approved.",items:["Services","Insurance","Vehicle brands","Location","Booking","Parts"]},
"spare-parts":{eyebrow:"Automobile Spare Parts",title:"Parts enquiries, made simple.",intro:"An inquiry-first parts experience. Live inventory or commerce can be connected later if required.",items:["Part requirement","Vehicle make / model","Quantity","Notes","Call / WhatsApp"]}
};
const services:Record<string,{eyebrow:string;title:string;intro:string;items:string[]}>={
"car-service":{eyebrow:"General Car Service & Repairs",title:"Keep the essentials running right.",intro:"Routine maintenance and mechanical repair intent, with a clear next action.",items:["Inspection","Diagnosis","Repair / service","Customer handover"]},
"car-ac-repair":{eyebrow:"Car AC Service & Repair",title:"A focused path for AC issues.",intro:"Clear local-search intent for car AC service and repair in Irinjalakuda.",items:["AC issue enquiry","Inspection","Repair / service","Book or call"]},
"accident-repair":{eyebrow:"Denting, Painting & Accident Repair",title:"From damage to the next step.",intro:"Accident repair, denting and painting with a direct bridge into insurance assistance.",items:["Damage description","Photo upload","Repair enquiry","Insurance assistance"]},
"denting-painting":{eyebrow:"Denting & Painting",title:"Bodywork with a clear process.",intro:"Dedicated bodywork journey for denting, painting and restoration enquiries.",items:["Damage assessment","Repair scope","Painting","Handover"]},
"wheel-alignment":{eyebrow:"Wheel Alignment, Balancing & Tyre Services",title:"Straighten out the details.",intro:"Computerized wheel alignment, balancing, tyre repair and rim repair are the verified capabilities in the supplied research.",items:["Wheel alignment","Wheel balancing","Tyre repair / puncture","Rim repair"]},
"tyre-services":{eyebrow:"Tyre Services",title:"Better contact with the road.",intro:"Dedicated route for tyre and balancing enquiries.",items:["Tyre enquiry","Balancing","Repair","Booking"]}
};

function Form({quote}:{quote:boolean}){return <div className="form"><div className="form-grid">{["Name","Phone","Vehicle make / model","Service needed"].map(x=><label key={x}>{x}<input placeholder={x}/></label>)}<label className="wide">Notes<textarea placeholder="Tell us what you need..."/></label>{quote&&<label className="upload wide"><Upload size={17}/>Upload damage / reference photos</label>}</div><button>Submit enquiry <ArrowUpRight size={16}/></button><small>Frontend form — routing/CRM/upload storage to be connected during technical discovery.</small></div>}

export default async function Page({params}:{params:Promise<{slug?:string[]}>}){
 const {slug=[]}=await params;const key=slug.join("/");
 if(key==="book-service"||key==="request-quote"){const quote=key==="request-quote";return <main className="inner-page"><div className="wrap narrow"><Link className="back" href="/"><ArrowLeft size={15}/>Back home</Link><span className="eyebrow">{quote?"Request a Quote":"Book a Service"}</span><h1 className="display page-title">{quote?"Tell us what needs fixing.":"Let's book your service."}</h1><p className="page-intro">{quote?"Use this route for service/parts enquiries and damage photos where applicable.":"Name, phone, vehicle, service and preferred date/time will feed the final booking workflow."}</p><Form quote={quote}/></div></main>}
 const item=services[key]||pages[key];
 if(!item)return <main className="inner-page"><div className="wrap narrow"><span className="eyebrow">404</span><h1 className="display page-title">Page not found.</h1><Link className="header-book" href="/">Back home</Link></div></main>;
 return <main className="inner-page"><div className="wrap narrow"><Link className="back" href="/"><ArrowLeft size={15}/>Back home</Link><span className="eyebrow">{item.eyebrow}</span><h1 className="display page-title">{item.title}</h1><p className="page-intro">{item.intro}</p><div className="detail-grid">{item.items.map((x,i)=><div className="detail-card" key={x}><small>{"0"+(i+1)}</small><h2>{x}</h2><Check size={17}/></div>)}</div><div className="inner-cta"><div><span className="eyebrow light">Next action</span><h2>Make the enquiry easy.</h2></div><div><Link href="/book-service/" className="primary-link">Book <ArrowUpRight size={16}/></Link><a href="tel:+919349002038" className="light-link"><Phone size={15}/>Call</a></div></div></div></main>;
}